{% set name = "ltbams" %}
{% set version = "1.0.13" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ltbams-{{ version }}.tar.gz
  sha256: d4908671484a8dbf3de5073140edf9d8dd05a34483cfd9912524b6a3e38d1f4c

build:
  entry_points:
    - ams = ams.cli:main
  script: |
    mv pyproject.toml pyproject.toml.bak
    {{ PYTHON }} -m pip install . --no-build-isolation --no-deps

    # === TEMPORARY FIX FOR CLOBBERWARNING ===
    # Remove the 'tests' directory after installation.
    # This works for noarch: python as the path is consistent.
    # $PREFIX is the build environment's installation prefix.
    # $PY_VER is the Python version.
    rm -rf "${PREFIX}/lib/python${PY_VER}/site-packages/tests"
    # ========================================

    mv pyproject.toml.bak pyproject.toml
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - kvxopt >=1.3.2.1
    - numpy
    - scipy
    - sympy >=1.6,!=1.10.0
    - pandas
    - matplotlib-base
    - psutil
    - openpyxl
    - andes >=1.9.3
    - pybind11
    - cvxpy
    - clarabel

test:
  imports:
    - ams
  commands:
    - pip check
    - ams st
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - cffi

about:
  home: https://github.com/CURENT/ams
  summary: Python software for scheduling modeling and co-simulation with dynamics.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://ltb.readthedocs.io/projects/ams/
  description: |
    AMS is a Python software designed for power system scheduling modeling and co-simulation with dynamics.
    It serves as the market simulator for the CURENT Largescale Testbed, enabling stability-constrained
    production cost and market operation modeling.

extra:
  recipe-maintainers:
    - jinningwang
