{% set name = "ltbams" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ltbams-{{ version }}.tar.gz
  sha256: 241792557051fbdfec5bbc36de0987296676ad8d3c607900475a74ab7bef37d2

build:
  entry_points:
    - ams = ams.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - kvxopt >=1.3.2.0
    - numpy
    - scipy
    - sympy >=1.6,!=1.10.0
    - pandas
    - matplotlib-base
    - psutil
    - openpyxl
    - andes >=1.8.7
    - pybind11
    - cvxpy
    - pyscipopt

test:
  imports:
    - ams
  commands:
    - pip check
    - ams st
  requires:
    - pip

about:
  home: https://github.com/CURENT/ams
  summary: Python software for dispatch modeling and co-simulation with dynanic.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://ltb.readthedocs.io/projects/ams/
  description: |
    AMS is a Python software designed for power system dispatch modeling and co-simulation with dynamics.
    It serves as the market simulator for the CURENT Largescale Testbed, enabling stability-constrained
    production cost and market operation modeling with credible dispatch results and competitive performance.

extra:
  recipe-maintainers:
    - jinningwang
