{% set name = "ltbams" %}
{% set version = "0.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ltbams-{{ version }}.tar.gz
  sha256: e99095153da21662e4b3ab930177044a8088a62fae21f9e7ed7563732416057a

build:
  entry_points:
    - ams = ams.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - kvxopt >=1.3.0.0,!=1.3.2.*
    - numpy
    - scipy
    - sympy >=1.6,<1.12,!=1.10.0
    - pandas
    - matplotlib-base
    - psutil
    - openpyxl
    - andes >=1.8.7,<=1.9.0
    - pybind11
    - cvxpy

test:
  imports:
    - ams
  commands:
    - pip check
    - ams --help
  requires:
    - pip

about:
  home: https://github.com/CURENT/ams
  summary: Python software for dispatch modeling and co-simulation with dynanic.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jinningwang
