{% set name = "ltbams" %}
{% set version = "1.0.10" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ltbams-{{ version }}.tar.gz
  sha256: f49f453e08334867fb5e79d855f7f2c6d305ef2b69ec03d2fda17d865142eb21

build:
  entry_points:
    - ams = ams.cli:main
  script: |
    mv pyproject.toml pyproject.toml.bak
    {{ PYTHON }} -m pip install . --no-build-isolation --no-deps
    mv pyproject.toml.bak pyproject.toml
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - kvxopt >=1.3.2.1
    - numpy
    - scipy
    - sympy >=1.6,!=1.10.0
    - pandas
    - matplotlib-base
    - psutil
    - openpyxl
    - andes >=1.9.3
    - pybind11
    - cvxpy

test:
  imports:
    - ams
  commands:
    - pip check
    - ams st
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/CURENT/ams
  summary: Python software for scheduling modeling and co-simulation with dynamics.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://ltb.readthedocs.io/projects/ams/
  description: |
    AMS is a Python software designed for power system scheduling modeling and co-simulation with dynamics.
    It serves as the market simulator for the CURENT Largescale Testbed, enabling stability-constrained
    production cost and market operation modeling.

extra:
  recipe-maintainers:
    - jinningwang
