{% set name = "ltbams" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ltbams-{{ version }}.tar.gz
  sha256: 901d29b9576eed1838c74aa864645c53dc3c8869c833b67ac96f98aaebf7701a

build:
  entry_points:
    - ams = ams.cli:main
  script: |
    mv pyproject.toml pyproject.toml.bak
    {{ PYTHON }} -m pip install . --no-build-isolation --no-deps
    mv pyproject.toml.bak pyproject.toml
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - kvxopt >=1.3.2.1
    - numpy
    - scipy
    - sympy >=1.6,!=1.10.0
    - pandas
    - matplotlib-base
    - psutil
    - openpyxl
    - andes >=1.8.7
    - pybind11
    - cvxpy
    - pyscipopt

test:
  imports:
    - ams
  commands:
    - pip check
    - ams st
  requires:
    - pip

about:
  home: https://github.com/CURENT/ams
  summary: Python software for scheduling modeling and co-simulation with dynamics.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://ltb.readthedocs.io/projects/ams/
  description: |
    AMS is a Python software designed for power system scheduling modeling and co-simulation with dynamics.
    It serves as the market simulator for the CURENT Largescale Testbed, enabling stability-constrained
    production cost and market operation modeling.

extra:
  recipe-maintainers:
    - jinningwang
