{% set name = "ltbams" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ltbams-{{ version }}.tar.gz
  sha256: 495ed5d8ff5b6008af9087b9d8e519905a81619b568dd34226038f8fcfd8ab09

build:
  entry_points:
    - ams = ams.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - kvxopt >=1.3.2.0
    - numpy
    - scipy
    - sympy >=1.6,<1.12,!=1.10.0
    - pandas
    - matplotlib-base
    - psutil
    - openpyxl
    - andes >=1.8.7
    - pybind11
    - cvxpy

test:
  imports:
    - ams
  commands:
    - pip check
    - ams st
  requires:
    - pip

about:
  home: https://github.com/CURENT/ams
  summary: Python software for dispatch modeling and co-simulation with dynanic.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jinningwang
