{% set name = "ltbams" %}
{% set version = "1.0.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ltbams-{{ version }}.tar.gz
  sha256: 3685d731454422c4f21f31d0cf5a46ed5b2bbafd771828a04dc876c34d3c72cd

build:
  entry_points:
    - ams = ams.cli:main
  script: |
    export SCIPOPTDIR=$PREFIX
    if [ ! -f "$PREFIX/lib/libscip.9.1.dylib" ]; then
      echo "SCIP library not found in $PREFIX/lib. Installing SCIP..."
      conda install -c conda-forge scip --prefix "$PREFIX"
    fi

    echo "Building and installing pyscipopt from Git source..."
    git clone https://github.com/scipopt/PySCIPOpt.git
    cd PySCIPOpt
    {{ PYTHON }} -m pip install . \
      --no-binary pyscipopt \
      --config-settings build_ext.include_dirs="$PREFIX/include/scip" \
      --config-settings build_ext.library_dirs="$PREFIX/lib"
    cd ..

    echo "Installing AMS package..."
    mv pyproject.toml pyproject.toml.bak
    {{ PYTHON }} -m pip install . --no-build-isolation --no-deps
    mv pyproject.toml.bak pyproject.toml
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - cython
    - scip
  run:
    - python >={{ python_min }}
    - kvxopt >=1.3.2.1
    - numpy
    - scipy
    - sympy >=1.6,!=1.10.0
    - pandas
    - matplotlib-base
    - psutil
    - openpyxl
    - andes >=1.9.3
    - pybind11
    - cvxpy
    - scip
    - pyscipopt

test:
  imports:
    - ams
  commands:
    - pip check
    - ams st
  requires:
    - python {{ python_min }}
    - pip
    - scip
    - pyscipopt

about:
  home: https://github.com/CURENT/ams
  summary: Python software for scheduling modeling and co-simulation with dynamics.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://ltb.readthedocs.io/projects/ams/
  description: |
    AMS is a Python software designed for power system scheduling modeling and co-simulation with dynamics.
    It serves as the market simulator for the CURENT Largescale Testbed, enabling stability-constrained
    production cost and market operation modeling.

extra:
  recipe-maintainers:
    - jinningwang
